name: "brick_crusher_challenge"
description: "Arcade game where the player controls a paddle at the bottom of the screen, bouncing a ball to break a wall of bricks at the top."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flame: ^1.16.0
  flame_audio: ^2.10.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
  - assets/audio/
